### PR TITLE
user can enroll in multiple courses

### PR DESCRIPTION
**Pull request by VaedaSolomon**
- a user can now be enrolled in multiple courses

- this info pulls to the dashboard (displays the courses the user is currently enrolled in below "Pick up where you left off")

- However, this messes up the dashboard design -- will need some front-end magic 🪄🔮

### CODE REVIEW

**Comment by VaedaSolomon** [comment]
Screenshot 2024-06-10 173254
Screenshot 2024-06-10 173324

**Comment by humayunk** [comment]
@VaedaSolomon can you update the logic so that on the dashboard the user only sees the most recent course they were learning

**Comment by VaedaSolomon** [comment]
- a user can now be enrolled in multiple courses

- this info pulls to the dashboard (displays the most recently accessed course below "Pick up where you left off")

**Review by humayunk — COMMENTED** [review]
LGTM

**Pull request merged**
